
class audience{
 
    Audiences()
    {
        cy.get('.h-full > :nth-child(1) > :nth-child(2)').realHover().wait(2000)
        cy.get('body').should('have.css', 'font').and('include','Poppins')
        cy.contains('Audiences').realHover().wait(1000).click().wait(2000)
        cy.get('body').should('have.css', 'font').and('include','Poppins')
        cy.url().should('include','/audiences').wait(1000)
        cy.get('nav.side-nav .top-nav-link .nav-link.active').realHover().wait(1000)
        cy.contains('Audiences').realHover().should('have.css','font-weight','700').realMouseMove(500,500)
        cy.get('nav.side-nav .top-nav-link .nav-link.active')
        .then(($el) => {
           const after = window.getComputedStyle($el[0], 'after'); 
           expect(after.getPropertyValue('background-color')).to.eq('rgb(255, 194, 28)')}).wait(1000)    
        cy.get('#audiences > .mb-8').scrollIntoView().wait(2000)
        cy.get(':nth-child(1) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','General Audiences')
        cy.get('.flex-wrap > [data-category="Technology"]').click().wait(2000)
        cy.get(':nth-child(2) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Technology Audiences')
        cy.get('.flex-wrap > [data-category="Design"]').click().wait(2000)
        cy.get(':nth-child(3) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Design Audiences')
        cy.get('.flex-wrap > [data-category="Games"]').click().wait(2000)
        cy.get(':nth-child(4) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Games Audiences')
        cy.get('.flex-wrap > [data-category="Home"]').click().wait(2000)
        cy.get(':nth-child(5) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Home Audiences')
        cy.get('.flex-wrap > [data-category="Health & Fitness"]').click().wait(2000)
        cy.get(':nth-child(6) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Health & Fitness Audiences')
        cy.get('.flex-wrap > [data-category="Pet"]').click().wait(2000)
        cy.get(':nth-child(7) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Pet Audiences')
        cy.get('.flex-wrap > [data-category="Children & Family"]').click().wait(2000)
        cy.get(':nth-child(8) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Children & Family Audiences')
        cy.get('.flex-wrap > [data-category="Publications"]').click().wait(2000)
        cy.get(':nth-child(9) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Publications Audiences')
        cy.get('.flex-wrap > [data-category="Green Tech"]').click().wait(2000)
        cy.get(':nth-child(10) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Green Tech Audiences')
        cy.get('.flex-wrap > [data-category="Outdoor & Travel"]').click().wait(2000)
        cy.get(':nth-child(11) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Outdoor & Travel Audiences')
        cy.get('.flex-wrap > [data-category="Other"]').click().wait(2000)
        cy.get(':nth-child(12) > .active_option > .min-w-full > thead > tr > :nth-child(1)').should('include.text','Other Audiences').wait(1000)
 }
    CreateAudienceDuplicateId()
    {
        cy.get('#audiences > .mb-8 > .mx-auto > .bkg-ylb').scrollIntoView().wait(2000).realHover().wait(1000).click().realMouseMove(100,100).wait(3000)
        cy.get('#facebook_audience_id').type('23854544333720614').wait(2000)
        cy.get('#name').type('Audience with Duplicate Id').wait(2000)
        cy.get('#description').type('Trying to create Audience with duplicate Audience Id').wait(2000)
        cy.get('#category_id').select('General',{scrollBehavior:false,force:true}).wait(2000)
        cy.get('.select2-selection').click().type('Faisal-Athar{enter}').wait(2000)
        cy.get('.bkg-ylb').realHover().wait(1000).click().realMouseMove(100,100).wait(2000)
        cy.get('.max-w-7xl > .flex').should('include.text','The facebook audience id has already been taken').wait(1000)
        cy.go(-2)

    }

    EditAudience()
    {
        cy.get('#audiences > .mb-8').scrollIntoView().wait(2000)
        cy.get('#audiences > :nth-child(4) > .shadow-xl > :nth-child(1) > .active_option > .min-w-full > .divide-y > tr > .text-right').click()
        cy.get('div > .absolute.z-50.mt-2.30.rounded-md.shadow-lg.origin-top-right.right-0').invoke('css', 'display', 'block').wait(2000)
        cy.contains('Edit Audience').realHover().wait(2000).click().realMouseMove(100,100).wait(3000)
        cy.get('#name').type('d').wait(2000)
        cy.get('#description').type('Editing Audience details...').wait(2000)
       // cy.get('#category_id').select('General')
        cy.get('.select2-selection').click().type('Faisal-Athar{enter}').wait(2000)
        cy.get('body').should('have.css', 'font').and('include','Poppins')
        cy.get('.bkg-ylb').realHover().wait(1000).click().realMouseMove(100,100).wait(3000)
        cy.get('#alert-1').should('include.text','Audience updated successfully')
    }
    
    ShareAudience()
    {
        cy.get('#audiences > .mb-8').scrollIntoView().wait(2000)
        cy.get('#audiences > :nth-child(4) > .shadow-xl > :nth-child(1) > .active_option > .min-w-full > .divide-y > tr > .w-72.px-3 > .w-72 > .button')
        .realHover({scrollBehavior:false}).wait(2000).click({scrollBehavior:false}).wait(5000)
        cy.get('#select2-project-container').click()
        cy.get('.select2-search__field').type('418786{enter}').wait(2000)
        cy.get('body').should('have.css', 'font').and('include','Poppins')
        cy.get('.py-3 > .border').realHover().wait(1000).click().wait(2000)
        cy.get('#audiences > .mb-8').should('be.visible').wait(1000)
        cy.get('#audiences > :nth-child(4) > .shadow-xl > :nth-child(1) > .active_option > .min-w-full > .divide-y > tr > .w-72.px-3 > .w-72 > .button')
        .realHover({scrollBehavior:false}).wait(2000).click({scrollBehavior:false}).wait(5000)
        cy.get('#select2-project-container').click()
        cy.get('.select2-search__field').type('418786{enter}').wait(2000)
        cy.get('.py-3 > .bkg-ylb').realHover().wait(1000).click().wait(6000)
        cy.get('#alert-1').scrollIntoView().wait(2000)
        cy.get('#alert-1').should('include.text','Audience shared successfully')
    }
    SharedAudiences()
    {
        cy.get('[data-tabs-target="#shared-audience"]').click({scrollBehavior:false}).wait(2000)
        cy.get('body').should('have.css', 'font').and('include','Poppins')
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(1) > .w-72 > .flex > .button').should('include.text','- Unshare Audiences').wait(1000)
        cy.get('.minh-label').click({scrollBehavior:false}).type('Testing Project',{scrollBehavior:false}).wait(3000)
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(1) > :nth-child(3)').should('include.text','Testing Project').wait(1000)
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(2) > :nth-child(3)').should('include.text','Testing Project').wait(1000)
        cy.get('.minh-label').clear({scrollBehavior:false}).wait(4000)
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(1) > .w-72 > .flex > .button')
        .realHover({scrollBehavior:false}).wait(2000).click({scrollBehavior:false}).realMouseMove(200,200).wait(2000)
        cy.get('.swal2-confirm').realHover().wait(2000).click().wait(5000)
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(1) > .w-72 > .flex > .basis-80p').should('include.text','Unshared Successfully')
        cy.get('#alert-1').scrollIntoView().wait(2000)
        cy.get('#alert-1').should('include.text','Audience unshared successfully')
        cy.get('.shadow-xl > .sm\\:px-6').scrollIntoView().wait(2000)
        cy.get("[aria-label='Go to page 2']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=2')
        cy.get("[aria-label='Go to page 3']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=3')
        cy.get("[aria-label='Go to page 4']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=4')
        cy.get("[aria-label='Go to page 5']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=5')
        cy.get("[aria-label='Go to page 6']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=6')
        cy.get("[aria-label='Go to page 7']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=7')
        cy.get("[aria-label='Go to page 8']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=8')       
        cy.get("[aria-label='Go to page 9']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=9')
        cy.get("[aria-label='Go to page 10']").click().wait(2000)
        cy.url().should('include','sharedAudiencePage=10')      
        cy.wait(5000)

    }
}
export default audience
