
class audience{
 
    PreCampaignAudiences()
    {
        cy.get(':nth-child(5) > .top-nav-link > .nav-link').realHover().wait(2000).click().realMouseMove(50,50)
        cy.wait(2000)
        cy.get('#audiences > .mb-8').scrollIntoView()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Technology"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Design"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Games"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Home"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Health & Fitness"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Pet"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Children & Family"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Publications"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Green Tech"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Outdoor & Travel"]').click()
        cy.wait(2000)
        cy.get('.flex-wrap > [data-category="Other"]').click()
       cy.wait(3000)
 }
    CreateAudienceDuplicateId()
    {
        cy.get('#audiences > .mb-8 > .mx-auto > .bkg-ylb').scrollIntoView().wait(2000).realHover().wait(1000).click().realMouseMove(100,100)
        cy.wait(3000)
        cy.get('#facebook_audience_id').type('23854544333720614')
        cy.wait(2000)
        cy.get('#name').type('Audience with Duplicate Id')
        cy.wait(2000)
        cy.get('#description').type('Trying to create Audience with duplicate Audience Id')
        cy.wait(2000)
        cy.get('#category_id').select('General',{scrollBehavior:false,force:true})
        cy.wait(2000)
        cy.get('.select2-selection').click().type('Faisal-Athar{enter}')
        cy.wait(2000)
        cy.get('.bkg-ylb').realHover().wait(1000).click().realMouseMove(100,100)
        cy.wait(1000)
        cy.get('.max-w-7xl > .flex').scrollIntoView()
        cy.wait(3000)
        cy.go(-2)

    }

    EditAudience()
    {
        cy.get('#audiences > .mb-8').scrollIntoView().wait(2000)
        cy.get('#audiences > :nth-child(4) > .shadow-xl > :nth-child(1) > .active_option > .min-w-full > .divide-y > tr > .text-right').click()
        cy.get('div > .absolute.z-50.mt-2.30.rounded-md.shadow-lg.origin-top-right.right-0').invoke('css', 'display', 'block')
        cy.wait(2000)
        cy.contains('Edit Audience').realHover().wait(2000).click().realMouseMove(100,100)
        cy.wait(3000)
        cy.get('#name').type('d')
        cy.wait(2000)
       // cy.get('#category_id').select('General')
        cy.get('.select2-selection').click().type('Faisal-Athar{enter}')
        cy.wait(2000)
        cy.get('.bkg-ylb').realHover().wait(2000).click().realMouseMove(100,100)
        cy.wait(1000)
        cy.get('#alert-1').scrollIntoView()
        cy.wait(3000)
    }
    
    ShareAudience()
    {
        cy.get('#audiences > .mb-8').scrollIntoView().wait(2000)
        cy.get('#audiences > :nth-child(4) > .shadow-xl > :nth-child(1) > .active_option > .min-w-full > .divide-y > tr > .w-72.px-3 > .w-72 > .button')
        .realHover({scrollBehavior:false}).wait(2000).click({scrollBehavior:false})
        cy.wait(3000)
        cy.get('#select2-project-container').click()
        cy.get('.select2-search__field').type('418786{enter}')
        cy.wait(1000)
        cy.get('.py-3 > .bkg-ylb').realHover().wait(1000).click()
        cy.wait(4000)
        cy.get('#alert-1').scrollIntoView()
        cy.wait(3000)
    }
    SharedAudiences()
    {
        cy.get('[data-tabs-target="#shared-audience"]').click({scrollBehavior:false})
        cy.wait(2000)
        cy.get('.minh-label').click({scrollBehavior:false}).type('Testing Project',{scrollBehavior:false})
        cy.wait(4000)
        cy.get('.minh-label').clear({scrollBehavior:false})
        cy.wait(4000)
        cy.get('.shadow-xl > .min-w-full > .bg-white > :nth-child(1) > .w-72 > .flex > .button').realHover({scrollBehavior:false}).wait(2000).click({scrollBehavior:false}).realMouseMove(200,200)
        cy.wait(2000)
        cy.get('.swal2-confirm').realHover().wait(2000).click()
        cy.wait(2000)
        cy.get('#alert-1').scrollIntoView()
        cy.wait(3000)
        cy.get('[aria-current="page"] > .relative').scrollIntoView()
        cy.wait(2000)
        cy.get(':nth-child(3) > .relative').click()
        cy.wait(2000)
        cy.get('.z-0 > :nth-child(4) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(5) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(6) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(7) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(8) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(9) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(10) > .relative').click()
        cy.wait(2000)
        cy.get(':nth-child(11) > .relative').click()
        cy.wait(2000)

    }
}
export default audience